version: '3.8'
services:
  mysql-cache:
    image: mysql:8.0 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cache_db
    ports:
      - "3306:3306"  # Map to your laptop's port 3306
    volumes:
      - mysql-data:/var/lib/mysql  # Persist data
    command: --default-authentication-plugin=mysql_native_password 
volumes:
  mysql-data: